Задание "Установить необходимые гемы для урока"
arzamaskov/TaskManager pull request #4
Opened 2021-12-27 07:08 UTC by arzamaskov

Установлены гемы, код проверен рубокопом

2021-12-27 15:27 UTC, greybutton requested changes

2021-12-27 15:27 UTC, greybutton commented on Gemfile
> +group :development, :test do
уже есть такая группа, добавь в нее гемы

2021-12-28 06:47 UTC, arzamaskov commented on Gemfile
> +group :development, :test do
Fixed

2021-12-28 18:29 UTC, greybutton commented on Gemfile
> +group :development, :test do
отправь занова на проверку в платформе

2021-12-29 05:13 UTC, arzamaskov commented on Gemfile
> +group :development, :test do
done

2021-12-29 06:30 UTC, greybutton approved these changes

2021-12-29 09:33 UTC, merged